# Generated by Django 4.2.8 on 2024-06-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('overview', models.TextField(verbose_name='新闻概要')),
                ('content', models.TextField(verbose_name='新闻正文')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='新闻发布时间')),
            ],
        ),
    ]
